# Generated by Django 2.0.1 on 2018-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=180, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=180, null=True)),
                ('baber_name', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
    ]
